### ISSUE TITLE
ucli git-wf 生成的内容不符合预期

### ISSUE THREAD

**Issue by ustinian-wang** [ustinian-wang/ucli#1]
## 复现步骤
- 执行如下命令：
```shell
$ ucli git-wf
? specify actions name u-ui
? specify branch of trigger action main
? specify shell, like yarn install && yarn build yarn build-storybook
? specify build directory storybook-static
```
- 生成为文件内容如下, 对应的部分的参数并没有被修改：
```yml
name: u-ui
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: yarn build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /storybook-static # The folder the action should deploy.
```

## 预期效果
执行命令后生成如下内容：
```yml
name: u-ui
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: yarn build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /storybook-static # The folder the action should deploy.
```
